# Generated by Django 4.0.5 on 2022-06-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='Homepage2 logo img')),
                ('name', models.CharField(max_length=100, verbose_name='Homepage2 name')),
                ('about', models.TextField(verbose_name='Homepage2 about')),
            ],
            options={
                'verbose_name': 'Home1',
                'verbose_name_plural': 'Homes1',
            },
        ),
        migrations.AlterField(
            model_name='homepage',
            name='name2',
            field=models.CharField(max_length=100, verbose_name='Homepage name2'),
        ),
    ]
