# Generated by Django 4.0.5 on 2022-06-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_aboutpage_about2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='Homepage1 logo img')),
                ('name', models.CharField(max_length=100, verbose_name='Homepage1 name')),
                ('about', models.TextField(verbose_name='Homepage1 about')),
            ],
            options={
                'verbose_name': 'Homepage1',
                'verbose_name_plural': 'Homepages1',
            },
        ),
    ]
