# Generated by Django 4.0.5 on 2022-06-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_homepage2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='Homepage3 logo img')),
                ('name', models.CharField(max_length=100, verbose_name='Homepage3 name')),
                ('price', models.IntegerField(verbose_name='Homepage3 about')),
            ],
            options={
                'verbose_name': 'Homepage3',
                'verbose_name_plural': 'Homepages3',
            },
        ),
    ]
