# Generated by Django 4.0.5 on 2022-06-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_homepage3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='Homepage4 logo img')),
                ('name', models.CharField(max_length=100, verbose_name='Homepage4 name')),
                ('about', models.TextField(verbose_name='Homepage4 about')),
            ],
            options={
                'verbose_name': 'Homepage4',
                'verbose_name_plural': 'Homepages4',
            },
        ),
        migrations.AlterField(
            model_name='homepage3',
            name='price',
            field=models.IntegerField(verbose_name='Homepage3 price'),
        ),
    ]
