# Generated by Django 4.0.5 on 2022-06-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_homepage4_alter_homepage3_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='Homepage5 about')),
                ('img', models.ImageField(upload_to='media', verbose_name='Homepage5 logo img')),
                ('name', models.CharField(max_length=100, verbose_name='Homepage5 name')),
            ],
            options={
                'verbose_name': 'Homepage5',
                'verbose_name_plural': 'Homepages5',
            },
        ),
    ]
