# Generated by Django 4.0.5 on 2022-06-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_homepage6'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutpag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='Aboutpag logo img')),
                ('name', models.CharField(max_length=100, verbose_name='Aboutpag name')),
                ('about', models.TextField(verbose_name='Aboutpag about')),
            ],
            options={
                'verbose_name': 'Aboutpag',
                'verbose_name_plural': 'Aboutpags',
            },
        ),
        migrations.DeleteModel(
            name='Aboutpage',
        ),
    ]
