# Generated by Django 4.0.5 on 2022-06-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_aboutnew_delete_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotelpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='Hotelpage logo img')),
                ('name', models.CharField(max_length=100, verbose_name='Hotelpage name')),
                ('about', models.TextField(verbose_name='Hotelpage about')),
            ],
            options={
                'verbose_name': 'Hotelpage',
                'verbose_name_plural': 'Hotelpages',
            },
        ),
    ]
