# Generated by Django 4.0.5 on 2022-06-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_hotelpage2_name2_hotelpage2_name3_hotelpage2_name4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='Blogpage logo img')),
                ('name', models.CharField(max_length=100, verbose_name='Blogpage name')),
            ],
            options={
                'verbose_name': 'Blogpage',
                'verbose_name_plural': 'Blogpages',
            },
        ),
    ]
