# Generated by Django 4.0.5 on 2022-06-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='name1',
            field=models.CharField(max_length=100, null=True, verbose_name='Blogpage name'),
        ),
    ]
