# Generated by Django 4.0.5 on 2022-06-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_blogpage_name1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpage1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='Blogpage1 logo img')),
                ('name', models.CharField(max_length=100, verbose_name='Blogpage1 name')),
                ('about', models.TextField(verbose_name='Blogpage1 name')),
            ],
            options={
                'verbose_name': 'Blogpage1',
                'verbose_name_plural': 'Blogpages1',
            },
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='name1',
            field=models.CharField(max_length=100, null=True, verbose_name='Blogpage name1'),
        ),
    ]
